#api

# imie_api_pc_all:
#     pattern:  /pc
#     defaults: { _controller: IMIEApiBundle:Pc:all}
#     requirements:
#         _method: GET

salle:
    type:     rest
    resource: "@IMIEApiBundle/Controller/SalleController.php"
    # resource: IMIE/ApiBundle/Controller/SalleController

pc:
    type:   rest
    resource:   "@IMIEApiBundle/Controller/PcController.php"
    # name_prefix:  api_

api_login_check:
    path: /login_check
    defaults:  { _controller: IMIEApiBundle:Default:index }